### PR TITLE
Support Dart 3.0

### PR DESCRIPTION
**Pull request by haashem**
Thanks for creating this helpful package,
I just updated the code to support Dart 3.0. and formatted code to be easier to read.

### CODE REVIEW

**Comment by lekanbar** [comment]
> Thanks for creating this helpful package, I just updated the code to support Dart 3.0. and formatted code to be easier to read.

Thanks @haashem for your contribution!

**Review by lekanbar — APPROVED** [review]
LGTM. Thank you!

**Comment by haashem** [comment]
Thanks for approving this PR. then please update this package in pub.dev 🙏

**Comment by lekanbar** [comment]
> Thanks for approving this PR. then please update this package in pub.dev 🙏

Yeah I'll try to do that this week, I'll keep you updated.

**Comment by lekanbar** [comment]
Hey @haashem, v0.3.0 is now available on pub.dev 🥳

**Comment by haashem** [comment]
That's great. Please add some example images to the readme, as it helps users to understand the package features.

**Pull request merged**
